version: '3'
services:
    server:
        container_name: ${COMPOSE_PROJECT_NAME}_server
        build:
            context: ./
            dockerfile: ./build/web/Dockerfile
            args:
                USERID: ${USERID}
                GROUPID: ${GROUPID}
                HOSTNAME: ${HOSTNAME}
        env_file:
            - .env
        volumes:
            - ./composer:/app/.composer
            - ./www:/app/www
#            - <absolute_path_to_oforge_folder>:/app/www
        ports:
            - ${HTTP_PORT}:9999
#        restart: always
        depends_on:
            - mysql

    adminer:
        container_name: ${COMPOSE_PROJECT_NAME}_adminer
        image: adminer
        environment:
            ADMINER_DEFAULT_SERVER: mysql
        ports:
            - ${ADMINER_PORT}:8080
#        restart: always
        depends_on:
            - mysql

    mysql:
        container_name: ${COMPOSE_PROJECT_NAME}_mysql
        build: ./build/mysql
        command: --default-authentication-plugin=mysql_native_password
#        restart: always
        env_file:
            - .env
#        volumes:
#            - ./build/mysql/data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - ${MYSQL_PORT}:3306
